extends Node

var dialogue_box = "/root/Game/Player/GUI/Control/DialogueBox"
var dialogue_label = "/root/Game/Player/GUI/Control/DialogueBox/MarginContainer/Label"
var problem = "/root/Game/Player/Problem"
var multiple_choice_tab = "/root/Game/Player/Problem/TabContainer/MultipleChoiceProblemTab"
var ci_tab = "/root/Game/Player/Problem/TabContainer/CIProblemTab"
var solution_tab = "/root/Game/Player/Problem/TabContainer/SolutionTab"
var multiple_choice_items = "/root/Game/Player/Problem/TabContainer/MultipleChoiceProblemTab/VBoxContainer"
var ci_items = "/root/Game/Player/Problem/TabContainer/CIProblemTab/VBoxContainer"
var solution_items = "/root/Game/Player/Problem/TabContainer/SolutionTab/VBoxContainer"
var stonks = "/root/Game/Player/GUI/Control/Overlays/Stonks"
var player = "/root/Game/Player"
var level_street = "/root/Game/LevelStreet"
var tilemap_level0 = "/root/Game/Level0/TileMapLayer2"
